cleanblog/urls.py
from django.urls import path
from . import views

app_name = "cleanblog"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("post/", views.PostView.as_view(), name="post"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path("sendmail/", views.sendmail, name="sendmail")
]

mysites/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("cleanblog/", include("cleanblog.urls")),
    path("polls/", include("polls.urls")),
    path("", RedirectView.as_view(url="cleanblog")),
    path("admin/", admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = "polls"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote")
]

cleanblog/models.py
from django.db import models

# Create your models here.

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

cleanblog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100, help_text="Must be filled")
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    email = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

    def sendmail(self):

        fullname = self.cleaned_data["name"]
        email = self.cleaned_data["email"]
        subject = self.cleaned_data["subject"]
        message = self.cleaned_data["message"] + "\nFrom: " + fullname + "\nEmail: " + email
        recipients = ["ihediohachidozie@gmail.com"]

        if not fullname:
            raise ValidationError(_('Invalid date - renewal in past'))

        send_mail(subject, message, email, recipients)

cleanblog/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.contrib import messages
from .forms import ContactForm


class HomeView(generic.TemplateView):
    template_name = "cleanblog/index.html"


class AboutView(generic.TemplateView):
    template_name = "cleanblog/about.html"


class PostView(generic.TemplateView):
    template_name = "cleanblog/post.html"


class ContactView(generic.TemplateView):
    template_name = "cleanblog/contact.html"


def sendmail(request):
    if request.method == "POST":
        form = ContactForm(request.POST)

        if form.is_valid():
            form.sendmail()
            messages.success(request, f'Thank you. Your message is sent!')
            return HttpResponseRedirect(reverse('cleanblog:contact'))
        else:
            # modify to send back the form with the error message..
            # return HttpResponse('bad content')
            form = ContactForm()
            return render(request, 'cleanblog/contact.html', {'form': form})

polls/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Question, Choice


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self) -> list:
        """Return the last 5 published questions"""
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/result.html"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(
            request,
            "polls/detail.html",
            {
               "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question_id,)))

cleanblog/templates/cleanblog/about.html
{% extends 'cleanblog/base.html' %}
{% load static %}
{% block title %} About {% endblock %}

{% block header %}
<header class="masthead" style="background-image: url('{% static 'cleanblog/assets/img/about-bg.jpg' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>About Me</h1>
                    <span class="subheading">This is what I do.</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur
                    voluptates odit, fuga
                    atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque
                    architecto error,
                    repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia
                    voluptas voluptatibus,
                    minus!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid
                    ex itaque esse
                    est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
            </div>
        </div>
    </div>
</main>
{% endblock %}

cleanblog/templates/cleanblog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    {% include 'cleanblog/inc/head.html' %}
    <body>
        <!-- Navigation-->
        {% include 'cleanblog/inc/nav.html' %}

        <!-- Page Header-->
        {% block header %} {% endblock %}

        <!-- Main Content-->
        {% block content %}{% endblock %}

        <!-- Footer-->
        {% include 'cleanblog/inc/footer.html' %}

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'cleanblog/js/scripts.js' %}"></script>
    </body>
</html>

cleanblog/templates/cleanblog/contact.html
{% extends 'cleanblog/base.html' %}
{% block title %} Contact Us {% endblock %}

{% load static %}
{% block header %}
<header class="masthead" style="background-image: url('{% static 'cleanblog/assets/img/contact-bg.jpg' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="page-heading">
                    <h1>Contact Me</h1>
                    <span class="subheading">Have questions? I have answers.</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block content %}
<!-- Main Content-->
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon
                    as possible!</p>
                <div class="my-5">
                    <!-- * * * * * * * * * * * * * * *-->
                    <!-- * * SB Forms Contact Form * *-->
                    <!-- * * * * * * * * * * * * * * *-->
                    <!-- This form is pre-integrated with SB Forms.-->
                    <!-- To make this form functional, sign up at-->
                    <!-- https://startbootstrap.com/solution/contact-forms-->
                    <!-- to get an API token!-->
                    <form id="contactForm" data-sb-form-api-token="API_TOKEN" method="post"
                          action="{% url 'cleanblog:sendmail' %}">
                        {% csrf_token %}
                        <div class="form-floating">
                            <input class="form-control" name="name" id="name" type="text"
                                   placeholder="Enter your name..." data-sb-validations="required"/>
                            <label for="name">Name</label>
                            {{ form.name.errors }}
                            <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                        </div>
                        <div class="form-floating">
                            <input class="form-control" name="email" id="email" type="email"
                                   placeholder="Enter your email..." data-sb-validations="required,email"/>
                            <label for="email">Email address</label>
                            <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                            <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                        </div>
                        <div class="form-floating">
                            <input class="form-control" name="subject" id="subject" type="tel"
                                   placeholder="Enter your subject..." data-sb-validations="required"/>
                            <label for="subject">Subject</label>
                            <div class="invalid-feedback" data-sb-feedback="phone:required">A subject is required.</div>
                        </div>
                        <div class="form-floating">
                            <textarea class="form-control" name="message" id="message"
                                      placeholder="Enter your message here..." style="height: 12rem"
                                      data-sb-validations="required"></textarea>
                            <label for="message">Message</label>
                            <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.
                            </div>
                        </div>
                        <br/>
                        <!-- Submit success message-->
                        <!---->
                        <!-- This is what your users will see when the form-->
                        <!-- has successfully submitted-->
                        {% if messages %}
                        {% for message in messages %}
                        <div class="text-center mb-3">
                            <div class="fw-bolder">{{ message }}</div>
                        </div>
                        {% endfor %}
                        {% endif %}


                        <!-- Submit error message-->
                        <!---->
                        <!-- This is what your users will see when there is-->
                        <!-- an error submitting the form-->
                        <div class="d-none" id="submitErrorMessage">
                            <div class="text-center text-danger mb-3">Error sending message!</div>
                        </div>
                        <!-- Submit Button-->
                        <button class="btn btn-primary text-uppercase" type="submit">Send</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

cleanblog/templates/cleanblog/inc/contact_footer.html
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>

cleanblog/templates/cleanblog/inc/footer.html
<footer class="border-top">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                        </a>
                    </li>
                </ul>
                <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website {% now "Y" %}</div>
            </div>
        </div>
    </div>
</footer>

cleanblog/templates/cleanblog/inc/head.html
{% load static %}
<head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - {% block title %} {% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="{% static 'cleanblog/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'cleanblog/css/styles.css' %}" rel="stylesheet" />
    </head>

cleanblog/templates/cleanblog/inc/nav.html
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'cleanblog:home' %}">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto py-4 py-lg-0">
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'cleanblog:home' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'cleanblog:about' %}">About</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'cleanblog:post' %}">Sample Post</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'cleanblog:contact' %}">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>

cleanblog/templates/cleanblog/index.html
{% extends 'cleanblog/base.html' %}
{% load static %}
{% block title %} Index {% endblock %}

{% block header %}
<header class="masthead" style="background-image: url('{% static 'cleanblog/assets/img/home-bg.jpg' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Clean Blog</h1>
                    <span class="subheading">A Blog Theme by Start Bootstrap</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block content %}
<main class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="post-preview">
                    <a href="{% url 'cleanblog:post' %}">
                        <h2 class="post-title">Man must explore, and this is exploration at its greatest</h2>
                        <h3 class="post-subtitle">Problems look mighty small from 150 miles up</h3>
                    </a>
                    <p class="post-meta">
                        Posted by
                        <a href="#!">Start Bootstrap</a>
                        on September 24, 2023
                    </p>
                </div>
                <!-- Divider-->
                <hr class="my-4"/>
                <!-- Post preview-->
                <div class="post-preview">
                    <a href="{% url 'cleanblog:post' %}"><h2 class="post-title">I believe every human has a finite number of heartbeats.
                        I don't intend
                        to waste any of mine.</h2></a>
                    <p class="post-meta">
                        Posted by
                        <a href="#!">Start Bootstrap</a>
                        on September 18, 2023
                    </p>
                </div>
                <!-- Divider-->
                <hr class="my-4"/>
                <!-- Post preview-->
                <div class="post-preview">
                    <a href="{% url 'cleanblog:post' %}">
                        <h2 class="post-title">Science has not yet mastered prophecy</h2>
                        <h3 class="post-subtitle">We predict too much for the next year and yet far too little for the
                            next ten.</h3>
                    </a>
                    <p class="post-meta">
                        Posted by
                        <a href="#!">Start Bootstrap</a>
                        on August 24, 2023
                    </p>
                </div>
                <!-- Divider-->
                <hr class="my-4"/>
                <!-- Post preview-->
                <div class="post-preview">
                    <a href="{% url 'cleanblog:post' %}">
                        <h2 class="post-title">Failure is not an option</h2>
                        <h3 class="post-subtitle">Many say exploration is part of our destiny, but it’s actually our
                            duty to future
                            generations.</h3>
                    </a>
                    <p class="post-meta">
                        Posted by
                        <a href="#!">Start Bootstrap</a>
                        on July 8, 2023
                    </p>
                </div>
                <!-- Divider-->
                <hr class="my-4"/>
                <!-- Pager-->
                <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older
                    Posts →</a></div>

            </div>
        </div>
    </div>
</main>
{% endblock %}

cleanblog/templates/cleanblog/post.html
{% extends 'cleanblog/base.html' %}
{% block title %} Post {% endblock %}
{% load static %}
{% block header %}
        <header class="masthead" style="background-image: url('{% static 'cleanblog/assets/img/post-bg.jpg' %}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="post-heading">
                            <h1>Man must explore, and this is exploration at its greatest</h1>
                            <h2 class="subheading">Problems look mighty small from 150 miles up</h2>
                            <span class="meta">
                                Posted by
                                <a href="#!">Start Bootstrap</a>
                                on August 24, 2023
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
{% endblock %}

{% block content %}
<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>Never in all their history have men been able truly to conceive of the world as one: a single sphere,
                    a globe, having the qualities of a globe, a round earth in which all the directions eventually meet,
                    in which there is no center because every point, or none, is center — an equal earth which all men
                    occupy as equals. The airman's earth, if free men make it, will be truly round: a globe in practice,
                    not in theory.</p>
                <p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no
                    turning back from science. The early warnings about technological dangers also come from
                    science.</p>
                <p>What was most significant about the lunar voyage was not that man set foot on the Moon but that they
                    set eye on the earth.</p>
                <p>A Chinese tale tells of some men sent to harm a young girl who, upon seeing her beauty, become her
                    protectors rather than her violators. That's how I felt seeing the Earth for the first time. I could
                    not help but love and cherish her.</p>
                <p>For those who have seen the Earth from space, and for the hundreds and perhaps thousands more who
                    will, the experience most certainly changes your perspective. The things that we share in our world
                    are far more valuable than those which divide us.</p>
                <h2 class="section-heading">The Final Frontier</h2>
                <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it
                    is a task to occupy the generations. And no matter how much progress one makes, there is always the
                    thrill of just beginning.</p>
                <p>There can be no thought of finishing for ‘aiming for the stars.’ Both figuratively and literally, it
                    is a task to occupy the generations. And no matter how much progress one makes, there is always the
                    thrill of just beginning.</p>
                <blockquote class="blockquote">The dreams of yesterday are the hopes of today and the reality of
                    tomorrow. Science has not yet mastered prophecy. We predict too much for the next year and yet far
                    too little for the next ten.
                </blockquote>
                <p>Spaceflights cannot be stopped. This is not the work of any one man or even a group of men. It is a
                    historical process which mankind is carrying out in accordance with the natural laws of human
                    development.</p>
                <h2 class="section-heading">Reaching for the Stars</h2>
                <p>As we got further and further away, it [the Earth] diminished in size. Finally it shrank to the size
                    of a marble, the most beautiful you can imagine. That beautiful, warm, living object looked so
                    fragile, so delicate, that if you touched it with a finger it would crumble and fall apart. Seeing
                    this has to change a man.</p>
                <a href="#!"><img class="img-fluid" src="{% static 'cleanblog/assets/img/post-sample-image.jpg' %}" alt="..."/></a>
                <span class="caption text-muted">To go places and do things that have never been done before – that’s what living is all about.</span>
                <p>Space, the final frontier. These are the voyages of the Starship Enterprise. Its five-year mission:
                    to explore strange new worlds, to seek out new life and new civilizations, to boldly go where no man
                    has gone before.</p>
                <p>As I stand out here in the wonders of the unknown at Hadley, I sort of realize there’s a fundamental
                    truth to our nature, Man must explore, and this is exploration at its greatest.</p>
                <p>
                    Placeholder text by
                    <a href="http://spaceipsum.com/">Space Ipsum</a>
                    &middot; Images by
                    <a href="https://www.flickr.com/photos/nasacommons/">NASA on The Commons</a>
                </p>
            </div>
        </div>
    </div>
</article>
{% endblock %}

polls/templates/polls/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>
<body>

{% block content %}

{% endblock %}

</body>
</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html' %}
{% block title %} Detail {% endblock %}

{% block content %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h2>{{question.question_text}}</h2></legend>
        {% if error_message %} <p> <strong>{{error_message }}</strong> </p> {% endif %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{choice.choice_text}}</label>
        <br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>


{% endblock %}

polls/templates/polls/index.html
{% extends 'polls/base.html' %}
{% block title %} Index {% endblock %}

{% block content %}
    {% if latest_question_list %}
        <ul>
            {% for question in latest_question_list %}
            <li>
                <a href="{% url 'polls:detail' question.id %}">
                    {{ question.question_text }}
                </a>
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available. </p>
    {% endif %}
{% endblock %}

polls/templates/polls/result.html
{% extends 'polls/base.html' %}
{% block title %} Result {% endblock %}

{% block content %}
    <h1>{{queston.question_text}}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
            <li>
                {{ choice.choice_text }} -- {{ choice.votes }} votes{{ choice.votes|pluralize }}
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}